	.\apm_config_out_mx[7] (i_ch02_mc_apm_config_in_mx_7_),
	.\apm_config_out_mx[6] (i_ch02_mc_apm_config_in_mx_6_),
	.\apm_config_out_mx[5] (i_ch02_mc_apm_config_in_mx_5_),
	.\apm_config_out_mx[4] (i_ch02_mc_apm_config_in_mx_4_),
	.\apm_config_out_mx[3] (i_ch02_mc_apm_config_in_mx_3_),
	.\apm_config_out_mx[2] (i_ch02_mc_apm_config_in_mx_2_),
	.\apm_config_out_mx[1] (i_ch02_mc_apm_config_in_mx_1_),
	.\apm_config_out_mx[0] (i_ch02_mc_apm_config_in_mx_0_),
