[6500500000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/u_ddrss_ch13_hm/VDDD_CH1_SS' transitioned to state 'DEFAULT_CORRUPT' with simstate 'CORRUPT'.
[6500500000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/VDDD_CH1_SS' transitioned to state 'DEFAULT_CORRUPT' with simstate 'CORRUPT'.
[6500500000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/VDDD_CH1_SS' transitioned to state 'DEFAULT_CORRUPT' with simstate 'CORRUPT'.
[6700500000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/u_ddrss_ch13_hm/VDDD_CH1_SS' transitioned to state 'DEFAULT_NORMAL' with simstate 'NORMAL'.
[6700500000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/VDDD_CH1_SS' transitioned to state 'DEFAULT_NORMAL' with simstate 'NORMAL'.
[6700500000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/VDDD_CH1_SS' transitioned to state 'DEFAULT_NORMAL' with simstate 'NORMAL'.
[9900500000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/u_ddrss_ch13_hm/VDDD_CH1_SS' transitioned to state 'DIG_NOM' with simstate 'NORMAL'.
[9900500000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/VDDD_CH1_SS' transitioned to state 'DIG_NOM' with simstate 'NORMAL'.
[9900500000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/VDDD_CH1_SS' transitioned to state 'DIG_NOM' with simstate 'NORMAL'.
[6665293744000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/u_ddrss_ch13_hm/VDDD_CH1_SS' transitioned to state 'DEFAULT_NORMAL' with simstate 'NORMAL'.
[6665293744000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/VDDD_CH1_SS' transitioned to state 'DEFAULT_NORMAL' with simstate 'NORMAL'.
[6665293744000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/VDDD_CH1_SS' transitioned to state 'DEFAULT_NORMAL' with simstate 'NORMAL'.
[6674450000000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/u_ddrss_ch13_hm/VDDD_CH1_SS' transitioned to state 'off' with simstate 'CORRUPT'.
[6674450000000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/VDDD_CH1_SS' transitioned to state 'off' with simstate 'CORRUPT'.
[6674450000000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/VDDD_CH1_SS' transitioned to state 'off' with simstate 'CORRUPT'.
[6883130000000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/u_ddrss_ch13_hm/VDDD_CH1_SS' transitioned to state 'DEFAULT_NORMAL' with simstate 'NORMAL'.
[6883130000000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/u_gen_slice_ddr_slice_ch/u_ddr_slice_ch/VDDD_CH1_SS' transitioned to state 'DEFAULT_NORMAL' with simstate 'NORMAL'.
[6883130000000 fs] [INFO] [LP_SS_STATE_CHANGE] Supply Set 'ddr_ss_synthetic_top_wrapper_dv/u_ddr_ss_synthetic_top_wrapper_dut_0/u_ddr_slice_hm_0/VDDD_CH1_SS' transitioned to state 'DEFAULT_NORMAL' with simstate 'NORMAL'.

considering this power rail-> VDDD_CH1_SS, is changing from 
CORRUPT->NORMAL->CORRUPT->NORMAL, this kind of notion should come for each and every rails from the input file, so script should search only LP_SS_STATE_CHANGE macthed lines, so that this can be achieved. 
